//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DcsWaypointExporter.CustomResources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DcsWaypointExporter.CustomResources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clipboard ähnelt.
        /// </summary>
        public static string Clipboard {
            get {
                return ResourceManager.GetString("Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DCS-Waypoint-Export file (*.dwe)|*.dwe|All files (*.*)|*.* ähnelt.
        /// </summary>
        public static string DialogFileFilterDWE {
            get {
                return ResourceManager.GetString("DialogFileFilterDWE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to save before exit? ähnelt.
        /// </summary>
        public static string DoYouWantToSaveBeforeExit {
            get {
                return ResourceManager.GetString("DoYouWantToSaveBeforeExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export ähnelt.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die From Clipboard ähnelt.
        /// </summary>
        public static string FromClipboard {
            get {
                return ResourceManager.GetString("FromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die From File ähnelt.
        /// </summary>
        public static string FromFile {
            get {
                return ResourceManager.GetString("FromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import ähnelt.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MIT License
        ///
        ///Copyright (c) 2024 Pixinger
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notic [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string LicenseMIT {
            get {
                return ResourceManager.GetString("LicenseMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load ähnelt.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Afghanistan ähnelt.
        /// </summary>
        public static string Map_Afghanistan {
            get {
                return ResourceManager.GetString("Map_Afghanistan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Caucasus ähnelt.
        /// </summary>
        public static string Map_Caucasus {
            get {
                return ResourceManager.GetString("Map_Caucasus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Map: ähnelt.
        /// </summary>
        public static string Map_COL {
            get {
                return ResourceManager.GetString("Map_COL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kola ähnelt.
        /// </summary>
        public static string Map_Kola {
            get {
                return ResourceManager.GetString("Map_Kola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nevada ähnelt.
        /// </summary>
        public static string Map_Nevada {
            get {
                return ResourceManager.GetString("Map_Nevada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Normandy 1944 ähnelt.
        /// </summary>
        public static string Map_Normandy1944 {
            get {
                return ResourceManager.GetString("Map_Normandy1944", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Normandy 2.0 ähnelt.
        /// </summary>
        public static string Map_Normandy2 {
            get {
                return ResourceManager.GetString("Map_Normandy2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Persian Gulf ähnelt.
        /// </summary>
        public static string Map_PersianGulf {
            get {
                return ResourceManager.GetString("Map_PersianGulf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sinai ähnelt.
        /// </summary>
        public static string Map_Sinai {
            get {
                return ResourceManager.GetString("Map_Sinai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die South Altlantic ähnelt.
        /// </summary>
        public static string Map_SouthAtlantic {
            get {
                return ResourceManager.GetString("Map_SouthAtlantic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Syria ähnelt.
        /// </summary>
        public static string Map_Syria {
            get {
                return ResourceManager.GetString("Map_Syria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Channel ähnelt.
        /// </summary>
        public static string Map_TheChannel {
            get {
                return ResourceManager.GetString("Map_TheChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Missions: ähnelt.
        /// </summary>
        public static string Missions_COL {
            get {
                return ResourceManager.GetString("Missions_COL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        public static string Name_COL {
            get {
                return ResourceManager.GetString("Name_COL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No valid mission data in the clipboard found. ähnelt.
        /// </summary>
        public static string NoValidMissionDataInTheClipboardFound {
            get {
                return ResourceManager.GetString("NoValidMissionDataInTheClipboardFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ok ähnelt.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Question ähnelt.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The clipboard content seems to be to large. Unable to open content larger than {0} MB. ähnelt.
        /// </summary>
        public static string TheClipboardContentSeemsToBeToLarge_UnableToOpenContentLargerThan_ARG0_Mb {
            get {
                return ResourceManager.GetString("TheClipboardContentSeemsToBeToLarge_UnableToOpenContentLargerThan_ARG0_Mb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file contains no valid mission data. ähnelt.
        /// </summary>
        public static string TheFileContainsNoValidMissionData {
            get {
                return ResourceManager.GetString("TheFileContainsNoValidMissionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file seems to be to large. Unable to open files larger than {0} MB. ähnelt.
        /// </summary>
        public static string TheFileSeemsToBeToLarge_UnableToOpenFilesLargerThan_ARG0_Mb {
            get {
                return ResourceManager.GetString("TheFileSeemsToBeToLarge_UnableToOpenFilesLargerThan_ARG0_Mb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To Clipboard ähnelt.
        /// </summary>
        public static string ToClipboard {
            get {
                return ResourceManager.GetString("ToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To File ähnelt.
        /// </summary>
        public static string ToFile {
            get {
                return ResourceManager.GetString("ToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to delete mission. ähnelt.
        /// </summary>
        public static string UnableToDeleteMission {
            get {
                return ResourceManager.GetString("UnableToDeleteMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to autodetect the &quot;SavedGames\Dcs&quot; folder. Please specify it manually in the appsettings.json. ähnelt.
        /// </summary>
        public static string UnableToDetectSavedGamesFolder {
            get {
                return ResourceManager.GetString("UnableToDetectSavedGamesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable generate mission export. ähnelt.
        /// </summary>
        public static string UnableToGenerateMissionExport {
            get {
                return ResourceManager.GetString("UnableToGenerateMissionExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to save modifications. ähnelt.
        /// </summary>
        public static string UnableToSaveModifications {
            get {
                return ResourceManager.GetString("UnableToSaveModifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Waypoints ähnelt.
        /// </summary>
        public static string Waypoints {
            get {
                return ResourceManager.GetString("Waypoints", resourceCulture);
            }
        }
    }
}
